import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";
import { Toaster } from "@/components/ui/sonner";



export const metadata: Metadata = {
  title: "AI notion clone",
  description: "Generated by create next app",
  

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      
    <html lang="en">
      <body>
        <Header />
        <div className="flex  min-h-screen">
          {/* Sidebar */}
            <SideBar />
          <div className="flex-1 p-4 bg-gray-100 overflow-y-auto scrollbar-hide">
        {children}
          </div>
        </div>
      <Toaster position="top-center"/>
      </body>
    </html>
    </ClerkProvider>
  );
}
